### ISSUE TITLE
Control Grammofon?

### ISSUE THREAD

**Issue by Rvanlaak** [benchmarkstudios/slackbox#4]
Will this be able to controll a [Grammofon](https://gramofon.com/) music player?  That would really be awesome!

**Comment by mikefrancis** [comment]
@Rvanlaak I think this might be a different use case.

From what I can see, Grammofon works via their own native app to access the network music controller.

Theoretically there's nothing to stop you using Grammofon to play a Spotify playlist which you then update via Slackbox, but you're then relying on Grammofon to stay in sync with the playlist.

In short; if you're a Grammofon user - I'd just use their native app.

**Comment by Rvanlaak** [comment]
Well, Spotify actually is the app that controls Grammofon, so since your app is able to control the playlist I thought this might be possible as well. But I think your plugin does not manipulate the playlist within Spotify right?

**Comment by mikefrancis** [comment]
@Rvanlaak Slackbox does exactly that - it adds tracks to the Spotify playlists via the API.

Like I said above, it's theoretically possible if Grammofon is synced to Spotify, however since Grammofon is controlled by their own native app - why would you want to introduce more complexity into this process?

**Comment by mikefrancis** [comment]
@bmsdan Think we can close this - if it doesn't work with Grammofon (which it should) it's a problem on their side which we have no control over.
